---
title: "HW2Ronquillo"
output: pdf_document
---

```{r}
#question1
#Consider the data in the file ch05q12.txt which shows the age of single child in years + months (two variables) as well the vocabulary size of the child. (Chapter 5, problem 12)

question1 = file.choose()
data = read.table(question1,header = T,sep = ",")
attach(data)

#a) Using both age variables, combine them into one variable for age in months. Create a scatter plot of the vocabulary size vs. age in months (your new variable). Based solely on the scatter plot, does a linear model seem appropriate?

AGE = (12*YEARS) + MONTHS
newvocab = cbind(data,AGE)
plot(newvocab$AGE,newvocab$VOC_SIZE)

  ### A linear model is appropriate based on the scatter plot. There seems to be a            positive linear relationship between vocabulary size and months.
```

```{r}
#b) write a regression model
fitvocab = lm(newvocab$VOC_SIZE~newvocab$AGE)
```

```{r}
#c) Using R, find the least squares estimates for the slope and intercept parameters. Write the equation final form of the least squares estimate line.
fitvocab = lm(newvocab$VOC_SIZE~newvocab$AGE)
summary(fitvocab)
  
  ### Intercept(Y) = -621.126
  ### newvocab$AGE(X) = 43.893
  
  ### LSE = -621.13 + 43.89x
```

```{r}
#d)interpret the intercept. Does the intercept make sense in the context of the problem?
sum(AGE = 0)

  ### since there is not a single occurrence when AGE = 0, the intercept does not make          sense
```

```{r}
#e) Using R, make a scatter plot with this line overlaying the graph.
plot(newvocab$AGE,newvocab$VOC_SIZE)
abline(lm(newvocab$VOC_SIZE~newvocab$AGE))
```

```{r}
#f) Add a new point to your data set (0,0) meaning the child at age 0 has no vocabulary. You either add it to the file and re-run your code or append it to your data frame. Recompute the least squares line and create just the scatter plot with the line overlayed. Does the model now seem appropriate?

newvocab2 = rbind(newvocab, c(0,0,0,0))
newfit = lm(VOC_SIZE~AGE, data = newvocab2)
summary(newfit)
plot(newvocab2$AGE,newvocab2$VOC_SIZE)
abline(lm(newvocab2$VOC_SIZE~newvocab2$AGE))

  ### LSE = -496.78 - 41.24x
  ### The model still appears to be relatively the same. There is just a point at 0,0     and the line shifted to left a little bit, it fits the points on the scatter plot       better but that's about it. 
```

```{r}
#g) Predict the vocabulary of a 30 year old using this model and compare this to the one you found above. Does this seem reasonable.

new <- data.frame(AGE = c(360))
predict(newfit, new)

  ### the predicted vocabulary of a 30 year old using this model is around 14,350 words.   This does seem reasonable, a little high but that's just because I myself don't know    how many words I know at the age of 22, but it is a lot. 

```

```{r}
#2)
n = 20
sumx = 90
sumy = 220
sumxsq = 145.8
sumysq = 2450.56
sumxy = 560.7
```

```{r}
#a) Calculate x and y
xbar = sumx/n
xbar
ybar = sumy/n
ybar
```
```{r}
#b)Determine the coefficients of a linear regression using the least squares method.
#Least square estimations of Bo and B1 
  
  #B1 = (sum(xy) - n(xbar)(ybar))/(sum(x^2) - n(xbar^2))
  #Bo = ybar - (B1)(xbar)

B1 = (sumxy - n*xbar*ybar)/((sumx**2) - (n*(xbar**2)))
B1

Bo = ybar - ((B1)*(xbar))
Bo
```
```{r}
#c) Calculate SSE and S^2 of y given x

  #SSE = SSY - (B1^2)SSX
    #SSY = (n-1)Sy^2
      #Sy^2 = (1/n-1)(sumy^2 - n*ybar^)
    #SSX = (n-1)Sx^2
      #Sx^2 = (1/n-1)(sumx^2 - n*xbar^2)
  
  #S^2 of y given x = MSE = SSE/n-2

Sy2 = (1/(n-1))*((sumy**2) - (n)*(ybar**2))
SSY = (n-1)*Sy2

Sx2 = (1/(n-1))*((sumx**2) - (n)*(xbar**2))
SSX = (n-1)*Sx2

SSE = SSY - (B1**2)*(SSX)
SSE

s2yx = SSE/(n-2)
s2yx
```

```{r}
#3a) Using R, create the linear regression for SBP(Y) regressed on QUET(X). Write the equation of the estimated regression line.
question3 = read.table(file.choose(),header = T,sep = ",")
X = question3$QUET
Y = question3$SBP
X0 = seq(min(X),max(X),by = (max(X) - min(X))/10)
xp = 3.4
n=length(X)

fit = lm(Y~X)
summary(fit)

  ### Y = 70.58 - 21.49x
```

```{r}
#b) Test the hypothesis that the slope parameter is 0 vs not 0. Write out the hypothesis. Use your R output to find the test statistic and p-value. State your conclusion.

fit = lm(Y~X)
summary(fit)

  ### Ho = 0 (null hypothesis is if the slope is = 0)
  ### Ha != 0 (alternative hypothesis is if the slope is not = 0)

  ### p value = 1.17e-06 or 0.000001172
  ### t statistic = 6.062

  ### since our p value = 0.000001172 < 0.05, we fail to reject the null hypothesis.          There is enough evidence to suggest that the slope parameter is not 0.
```

```{r}
#c) Using R, make a scatter plot of the data with the regression line included on the plot. Create the 95 % prediction interval and include this on the plot.

mse = sum(fit$residuals^2)/(n - 2)

slopelow = fit$coefficients[2] -qt(0.975,n-2)*sqrt(mse)/(sd(X)*sqrt(n-1))
slopehigh = fit$coefficients[2] +qt(0.975,n-2)*sqrt(mse)/(sd(X)*sqrt(n-1)) 

ylow = fit$coefficients[1] + fit$coefficients[2]*X0 -
  qt(0.975,n-2)*sqrt(mse)*sqrt(1/n + (X0 - mean(X))^2/((n-1)*var(X)))
yhigh = fit$coefficients[1] + fit$coefficients[2]*X0 +qt(0.975,n-2)*sqrt(mse)*
  sqrt(1/n + (X0 - mean(X))^2/((n-1)*var(X)))
ypredlow = fit$coefficients[1] + fit$coefficients[2]*X0 -qt(0.975,n-2)*
  sqrt(mse)*sqrt(1+ 1/n + (X0 - mean(X))^2/((n-1)*var(X)))
ypredhigh =fit$coefficients[1] + fit$coefficients[2]*X0 +qt(0.975,n-2)*
  sqrt(mse)*sqrt(1+ 1/n + (X0 - mean(X))^2/((n-1)*var(X)))

plot(Y~X)
abline(fit)
lines(X0,ylow,col="red")
lines(X0,yhigh,col="red")
lines(X0,ypredlow,col="blue")
lines(X0,ypredhigh,col="blue")

yhat = fit$coefficients[1] + fit$coefficients[2]*xp
ylowp = fit$coefficients[1] + fit$coefficients[2]*xp -
  qt(0.975,n-2)*sqrt(mse)*sqrt(1/n + (xp - mean(X))^2/((n-1)*var(X)))
yhighp = fit$coefficients[1] + fit$coefficients[2]*xp +qt(0.975,n-2)*
  sqrt(mse)*sqrt(1/n + (xp - mean(X))^2/((n-1)*var(X)))

ypredlowp = fit$coefficients[1] + fit$coefficients[2]*xp -qt(0.975,n-2)*
  sqrt(mse)*sqrt(1+ 1/n + (xp - mean(X))^2/((n-1)*var(X)))
ypredhighp =fit$coefficients[1] + fit$coefficients[2]*xp +qt(0.975,n-2)*
  sqrt(mse)*sqrt(1+ 1/n + (xp - mean(X))^2/((n-1)*var(X)))
```

```{r}
#d) Predict the SBP of a person with a QUET = 3.4. Calculate a the 95% prediction interval around this predicted value and interpret.

new <- data.frame(X = c(3.4))
fit3d = lm(Y~X, data = question3)
predict(fit3d, new, interval = 'confidence') 

  ### We are 95% confident that the SBP of a person with a QUET of 3.4 is between the         interval (140.09, 147.20)
```













